services:
  con4gis_pwa_manifest:
    class: con4gis\PwaBundle\Classes\Services\ManifestCreationService
    public: true
    arguments: ['%contao.web_dir%']

  con4gis_pwa_service_worker:
    class: con4gis\PwaBundle\Classes\Services\ServiceWorkerCreationService
    public: true
    arguments: ['%contao.web_dir%', '@service_container']

  con4gis_pwa.sendPushCommand:
    class: con4gis\PwaBundle\Command\SendPushNotificationCommand
    tags:
      - { name: console.command }
    arguments:
      - '@service_container'
      - '@minishlink_web_push'

  pwa.onPushNotificationGetSubscriptions:
    class: con4gis\PwaBundle\Classes\Listener\PushNotificationListener
    tags:
      - { name: kernel.event_listener, event: con4gis.notification.send, method: onPushNotificationGetSubscriptions, priority: 2048 }
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '@minishlink_web_push'

  pwa.onPushNotificationSendNotifications:
    class: con4gis\PwaBundle\Classes\Listener\PushNotificationListener
    tags:
      - { name: kernel.event_listener, event: con4gis.notification.send, method: onPushNotificationSendNotifications, priority: 1024 }
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '@minishlink_web_push'